name: External Links Checker
on:
  schedule:
    - cron: '30 18 * * *' # everyday 18:30 UTC
  workflow_dispatch:
jobs:
  external-links:
    name: Check external links
    if: github.repository == 'OpenLightingProject/open-fixture-library'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Node.js v20
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check external links
        run: node --tls-min-v1.0 tests/external-links.js
        env:
          GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BROKEN_LINKS_ISSUE_NUMBER: 999
          NODE_ENV: production
      - name: Check Markdown Links in all files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
